=== jbantequera/lmsgi-xml/tiempo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element="weather">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="city" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="coord">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="lon" type="xs:decimal" />
									<xs:element name="lat" type="xs:decimal" />
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="weather">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="id" type="xs:integer" />
									<xs:element name="main" type="xs:string" />
									<xs:element name="description" type="xs:string" />
									<xs:element name="icon" type="xs:string" />
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="base" type="xs:string" />
						<xs:element name="main">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="temp" type="xs:decimal" />
									<xs:element name="pressure" type="xs:integer" />
									<xs:element name="humidity" type="xs:integer" />
									<xs:element name="temp_min" type="xs:decimal" />
									<xs:element name="temp_max" type="xs:decimal" />
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="visibility" type="xs:integer" />
						<xs:element name="wind">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="speed" type="xs:decimal" />
									<xs:element name="deg" type="xs:integer" />
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="clouds">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="all" type="xs:integer" />
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="dt" type="xs:integer" />
						<xs:element name="sys">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="type" type="xs:integer" />
									<xs:element name="id" type="xs:integer" />
									<xs:element name="message" type="xs:decimal" />
									<xs:element name="country" type="xs:string" />
									<xs:element name="sunrise" type="xs:integer" />
									<xs:element name="sunset" type="xs:integer" />
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="id" type="xs:integer" />
						<xs:element name="name" type="xs:string" />
						<xs:element name="cod" type="xs:integer" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:element>

=== jbantequera/lmsgi-xml/tiempo.xml
<?xml version="1.0" encoding="UTF-8"?>
<weather xmlns="https://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="file:///C:/Users/josegras/Desktop/lmsgi-xml/tiempo.xsd">
	<city>
		<coord>
			<lon>-0.13</lon>
			<lat>51.51</lat>
		</coord>
		<weather>
			<id>300</id>
			<main>Drizzle</main>
			<description>light intensity drizzle</description>
			<icon>09d</icon>
		</weather>
		<base>stations</base>
		<main>
			<temp>280.32</temp>
			<pressure>1012</pressure>
			<humidity>81</humidity>
			<temp_min>279.15</temp_min>
			<temp_max>281.15</temp_max>
		</main>
		<visibility>10000</visibility>
		<wind>
			<speed>4.1</speed>
			<deg>80</deg>
		</wind>
		<clouds>
			<all>90</all>
		</clouds>
		<dt>1485789600</dt>
		<sys>
			<type>1</type>
			<id>5091</id>
			<message>0.0103</message>
			<country>GB</country>
			<sunrise>1485762037</sunrise>
			<sunset>1485794875</sunset>
		</sys>
		<id>2643743</id>
		<name>London</name>
		<cod>200</cod>
	</city>
</weather>
